### PR TITLE
Update to newer installs and extending integration test.

### PR DESCRIPTION
**Pull request by jlingema**
Moving to new install of fcc-edm (v0.4), podio (v0.4) and DD4hep (trunk from 2016-10-03).

### CODE REVIEW

**Comment by jlingema** [comment]
Also updated the version of DD4hep that is used (only needed if used in conjunction with FCCSW)

**Comment by hegner** [comment]
@jlingema - what procedures did you do for testing?

**Comment by jlingema** [comment]
I used the "test_master.sh" with this updated init. 

That means I checked FCC-Delphes (write) -> fcc-physics (read), fcc-physics -pythia (write) -> heppy (read) + any tests we have in the individual repositories.

**Comment by hegner** [comment]
@jlingema - thanks. Not sure that has sufficient DD4hep coverage. Could you add a corresponding test?

**Comment by jlingema** [comment]
@hegner - we have some tests [in FCCSW](https://github.com/HEP-FCC/FCCSW/blob/master/DetectorDescription/DetSensitive/CMakeLists.txt) that compare standalone Geant 4 with DD4hep (thanks to @zaborowska).

**Comment by hegner** [comment]
@jlingema @zaborowska - thanks!

**Comment by jlingema** [comment]
@hegner - so after a quick discussion with Anna (@zaborowska), we do have some tests (for the sensitive detectors) but nothing that does a full comparison, it will be added to FCCSW. However, she ran some comparisons by hand (note that these comparisons are not possible with the older version of DD4hep, since the segmentation is broken there).

**Comment by jlingema** [comment]
@hegner - Can we merge this?

**Comment by jlingema** [comment]
1. Added tests to Jenkins that now run the init script and compile FCCSW against cvmfs / afs when a PR is done
2. With the last commits, it is now also possible to extend the Jenkins nightly that runs the examples from the tutorials to test with:
   1. the centrally installed versions on afs / cvmfs (of fcc-edm, podio, and fcc-physics).
   2. the current masters of all repositories

**Pull request merged**
