### PR TITLE
Source CMake from LCG/contrib

### PR DESCRIPTION
**Pull request by JavierCVilla**
Setup CMake provided by LCG/contrib, which is the one used to build the LCG releases.

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi Javier, I'm not sure what `config/setup.tpl` is used for, but shouldn't cmake be available via the lcg view?

**Comment by JavierCVilla** [comment]
`config/setup.tpl` is the template file we use to create `setup.sh`, which is the one that sources a view. 
Indeed, `cmake` it is provided by the LCG view, however the `cmake` version used to build the LCG Release 93 and the one provided *with* that release are different, hence I'm having issues at configuration time building FCCSW. 

As far as I know, LCG team is already building using a newer version of CMake (`3.11.1`) which is already included on the nightlies. For the time being, we can take the version provided on LCG/contrib and switch back again to the released cmake once both versions (the one they use and the one provided) match, i.e. for the next release.

**Comment by vvolkl** [comment]
Ok, thanks for the explanation! Can you add a quick comment in the code?

**Review by vvolkl — CHANGES_REQUESTED** [review]
Thanks! Can you add a quick comment about the cmake version mismatch and when/if this should be updated in the future?

**Comment by JavierCVilla** [comment]
Ups, @vvolkl I just amended my last commit after your comment.

**Comment by vvolkl** [comment]
@JavierCVilla   seems like you still need to push the amended commit!

**Comment by JavierCVilla** [comment]
@vvolkl true, done now

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
